image: node:6.9

cache:
  paths:
  - node_modules/

before_script:
  - npm install

build:
  script:
    - npm run build

deploy:
  script:
    - npm run build
    - git push prod master
  
  only:
    - master